export type VehicleModelType =
  | 'CAR'
  | 'SUV'
  | 'PICKUP'
  | 'VAN'
  | 'SMALL_TRUCK'
  | 'MEDIUM_TRUCK'
  | 'TOW_TRUCK'
  | 'OPEN_CAR_CARRIER'
  | 'ENCLOSED_CARRIER'
  | 'MOTORCYCLE';

export const VEHICLE_MODELS_BY_BRAND_AND_TYPE = {
  Toyota: {
    CAR: ['Yaris', 'Corolla', 'Camry', 'Avalon', 'Prius', 'Crown'],
    SUV: [
      'Raize',
      'C-HR',
      'RAV4',
      'Highlander',
      'Fortuner',
      'Land Cruiser Prado',
      'Land Cruiser',
      'Sequoia',
    ],
    PICKUP: ['Hilux', 'Tacoma', 'Tundra'],
    VAN: ['Hiace', 'Proace', 'Sienna', 'Granvia', 'Alphard'],
    SMALL_TRUCK: ['Dyna', 'ToyoAce', 'LiteAce Truck'],
    MEDIUM_TRUCK: ['Dyna', 'ToyoAce', 'Other Toyota chassis'],
    TOW_TRUCK: ['Dyna', 'ToyoAce', 'Other Toyota chassis'],
    OPEN_CAR_CARRIER: ['Dyna', 'Other Toyota chassis'],
    ENCLOSED_CARRIER: ['Other Toyota chassis'],
    MOTORCYCLE: [],
  },
  Nissan: {
    CAR: ['Sunny', 'Sentra', 'Altima', 'Maxima', 'Micra', 'Versa', 'Tiida', 'Note'],
    SUV: [
      'Kicks',
      'Juke',
      'Qashqai',
      'X-Trail',
      'Rogue',
      'Pathfinder',
      'Patrol',
      'Armada',
      'Murano',
      'Terra',
    ],
    PICKUP: ['Navara', 'Frontier', 'NP300', 'Titan'],
    VAN: ['Urvan', 'NV200', 'NV350', 'Caravan', 'NV1500', 'NV2500', 'NV3500'],
    SMALL_TRUCK: ['Cabstar', 'Atlas', 'NT400'],
    MEDIUM_TRUCK: ['NT500', 'Atlas', 'Cabstar'],
    TOW_TRUCK: ['Cabstar', 'Atlas', 'NT400', 'NT500', 'Other Nissan chassis'],
    OPEN_CAR_CARRIER: ['Other Nissan chassis'],
    ENCLOSED_CARRIER: ['Other Nissan chassis'],
    MOTORCYCLE: [],
  },
  Ford: {
    CAR: ['Fiesta', 'Focus', 'Fusion', 'Mondeo', 'Taurus', 'Mustang'],
    SUV: ['EcoSport', 'Escape', 'Kuga', 'Edge', 'Explorer', 'Expedition', 'Bronco', 'Everest'],
    PICKUP: ['Ranger', 'Maverick', 'F-150', 'F-250', 'F-350'],
    VAN: ['Transit', 'Transit Connect', 'Tourneo', 'E-Series'],
    SMALL_TRUCK: ['Transit Chassis Cab', 'E-Series Cutaway'],
    MEDIUM_TRUCK: ['F-450', 'F-550', 'F-650', 'F-750'],
    TOW_TRUCK: ['F-350', 'F-450', 'F-550', 'F-650', 'Other Ford chassis'],
    OPEN_CAR_CARRIER: ['F-450', 'F-550', 'F-650', 'Other Ford chassis'],
    ENCLOSED_CARRIER: ['F-650', 'F-750', 'Other Ford chassis'],
    MOTORCYCLE: [],
  },
  Chevrolet: {
    CAR: ['Spark', 'Aveo', 'Sonic', 'Cruze', 'Malibu', 'Impala', 'Camaro', 'Corvette'],
    SUV: ['Trax', 'Captiva', 'Equinox', 'Blazer', 'Traverse', 'Tahoe', 'Suburban'],
    PICKUP: ['Colorado', 'Silverado 1500', 'Silverado 2500HD', 'Silverado 3500HD'],
    VAN: ['Express 2500', 'Express 3500', 'City Express'],
    SMALL_TRUCK: ['Express Cutaway', 'Low Cab Forward 3500'],
    MEDIUM_TRUCK: [
      'Low Cab Forward 4500',
      'Low Cab Forward 5500',
      'Silverado 4500HD',
      'Silverado 5500HD',
      'Silverado 6500HD',
    ],
    TOW_TRUCK: [
      'Silverado 3500HD',
      'Silverado 4500HD',
      'Silverado 5500HD',
      'Silverado 6500HD',
      'Other Chevrolet chassis',
    ],
    OPEN_CAR_CARRIER: [
      'Silverado 4500HD',
      'Silverado 5500HD',
      'Silverado 6500HD',
      'Other Chevrolet chassis',
    ],
    ENCLOSED_CARRIER: ['Silverado 6500HD', 'Other Chevrolet chassis'],
    MOTORCYCLE: [],
  },
  GMC: {
    CAR: [],
    SUV: ['Terrain', 'Acadia', 'Yukon', 'Yukon XL'],
    PICKUP: ['Canyon', 'Sierra 1500', 'Sierra 2500HD', 'Sierra 3500HD'],
    VAN: ['Savana 2500', 'Savana 3500'],
    SMALL_TRUCK: ['Savana Cutaway'],
    MEDIUM_TRUCK: ['Sierra 3500HD Chassis Cab', 'TopKick', 'C-Series'],
    TOW_TRUCK: ['Sierra 3500HD', 'Savana Cutaway', 'TopKick', 'Other GMC chassis'],
    OPEN_CAR_CARRIER: ['TopKick', 'Other GMC chassis'],
    ENCLOSED_CARRIER: ['TopKick', 'Other GMC chassis'],
    MOTORCYCLE: [],
  },
  RAM: {
    CAR: [],
    SUV: [],
    PICKUP: ['RAM 1500', 'RAM 2500', 'RAM 3500'],
    VAN: ['ProMaster City', 'ProMaster 1500', 'ProMaster 2500', 'ProMaster 3500'],
    SMALL_TRUCK: ['ProMaster Chassis Cab', 'RAM 3500 Chassis Cab'],
    MEDIUM_TRUCK: ['RAM 3500 Chassis Cab', 'RAM 4500 Chassis Cab', 'RAM 5500 Chassis Cab'],
    TOW_TRUCK: ['RAM 3500', 'RAM 4500', 'RAM 5500', 'Other RAM chassis'],
    OPEN_CAR_CARRIER: ['RAM 4500', 'RAM 5500', 'Other RAM chassis'],
    ENCLOSED_CARRIER: ['RAM 5500', 'Other RAM chassis'],
    MOTORCYCLE: [],
  },
  Isuzu: {
    CAR: [],
    SUV: ['MU-X', 'Trooper', 'Axiom'],
    PICKUP: ['D-Max', 'TF'],
    VAN: [],
    SMALL_TRUCK: ['NLR', 'NMR', 'NPR'],
    MEDIUM_TRUCK: ['NQR', 'NRR', 'FRR', 'FTR', 'FVR', 'FXR'],
    TOW_TRUCK: ['NPR', 'NQR', 'NRR', 'FRR', 'FTR', 'Other Isuzu chassis'],
    OPEN_CAR_CARRIER: ['NPR', 'NQR', 'NRR', 'FTR', 'Other Isuzu chassis'],
    ENCLOSED_CARRIER: ['NQR', 'NRR', 'FTR', 'Other Isuzu chassis'],
    MOTORCYCLE: [],
  },
  Mitsubishi: {
    CAR: ['Mirage', 'Attrage', 'Lancer', 'Galant'],
    SUV: ['ASX', 'Eclipse Cross', 'Outlander', 'Pajero', 'Montero'],
    PICKUP: ['L200', 'Triton'],
    VAN: ['Delica', 'L300', 'Express'],
    SMALL_TRUCK: ['Canter', 'L200 Chassis'],
    MEDIUM_TRUCK: ['Canter', 'Fighter'],
    TOW_TRUCK: ['Canter', 'Fighter', 'Other Mitsubishi chassis'],
    OPEN_CAR_CARRIER: ['Canter', 'Fighter', 'Other Mitsubishi chassis'],
    ENCLOSED_CARRIER: ['Canter', 'Fighter', 'Other Mitsubishi chassis'],
    MOTORCYCLE: [],
  },
  Hyundai: {
    CAR: ['i10', 'i20', 'i30', 'Accent', 'Elantra', 'Sonata', 'Azera', 'Veloster'],
    SUV: ['Venue', 'Kona', 'Tucson', 'Santa Fe', 'Palisade', 'Creta'],
    PICKUP: ['Santa Cruz'],
    VAN: ['H-1', 'H100', 'Starex', 'Staria'],
    SMALL_TRUCK: ['Porter', 'H100', 'Mighty'],
    MEDIUM_TRUCK: ['Mighty', 'Mega Truck', 'Pavise'],
    TOW_TRUCK: ['Porter', 'Mighty', 'Mega Truck', 'Other Hyundai chassis'],
    OPEN_CAR_CARRIER: ['Mighty', 'Mega Truck', 'Other Hyundai chassis'],
    ENCLOSED_CARRIER: ['Mighty', 'Mega Truck', 'Other Hyundai chassis'],
    MOTORCYCLE: [],
  },
  Kia: {
    CAR: ['Picanto', 'Rio', 'Cerato', 'Forte', 'K3', 'K5', 'Optima', 'Cadenza', 'Stinger'],
    SUV: ['Soul', 'Stonic', 'Seltos', 'Sportage', 'Sorento', 'Telluride', 'Mohave'],
    PICKUP: ['Tasman'],
    VAN: ['Carnival', 'Carens', 'Bongo', 'Pregio'],
    SMALL_TRUCK: ['Bongo', 'K2500', 'K2700', 'K3000'],
    MEDIUM_TRUCK: ['K3000', 'K4000', 'K-Series Truck'],
    TOW_TRUCK: ['Bongo', 'K2500', 'K2700', 'K3000', 'Other Kia chassis'],
    OPEN_CAR_CARRIER: ['K3000', 'K4000', 'Other Kia chassis'],
    ENCLOSED_CARRIER: ['Other Kia chassis'],
    MOTORCYCLE: [],
  },
  'Mercedes-Benz': {
    CAR: ['A-Class', 'B-Class', 'C-Class', 'E-Class', 'S-Class', 'CLA', 'CLS', 'SL', 'AMG GT'],
    SUV: ['GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'G-Class'],
    PICKUP: ['X-Class'],
    VAN: ['Citan', 'Vito', 'V-Class', 'Sprinter'],
    SMALL_TRUCK: ['Sprinter Chassis Cab', 'Atego'],
    MEDIUM_TRUCK: ['Atego', 'Axor', 'Actros', 'Arocs', 'Econic'],
    TOW_TRUCK: [
      'Sprinter Chassis Cab',
      'Atego',
      'Axor',
      'Actros',
      'Arocs',
      'Other Mercedes-Benz chassis',
    ],
    OPEN_CAR_CARRIER: ['Atego', 'Axor', 'Actros', 'Other Mercedes-Benz chassis'],
    ENCLOSED_CARRIER: ['Atego', 'Actros', 'Other Mercedes-Benz chassis'],
    MOTORCYCLE: [],
  },
  BMW: {
    CAR: ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'Z4', 'i3', 'i4', 'i5', 'i7'],
    SUV: ['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'iX'],
    PICKUP: [],
    VAN: [],
    SMALL_TRUCK: [],
    MEDIUM_TRUCK: [],
    TOW_TRUCK: [],
    OPEN_CAR_CARRIER: [],
    ENCLOSED_CARRIER: [],
    MOTORCYCLE: ['G 310 R', 'G 310 GS', 'F 750 GS', 'F 850 GS', 'F 900 R', 'F 900 XR', 'R 1250 GS', 'R 1300 GS', 'R 1250 RT', 'S 1000 RR', 'S 1000 R', 'K 1600'],
  },
  Audi: {
    CAR: ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'TT', 'R8', 'e-tron GT'],
    SUV: ['Q2', 'Q3', 'Q4 e-tron', 'Q5', 'Q7', 'Q8', 'e-tron'],
    PICKUP: [],
    VAN: [],
    SMALL_TRUCK: [],
    MEDIUM_TRUCK: [],
    TOW_TRUCK: [],
    OPEN_CAR_CARRIER: [],
    ENCLOSED_CARRIER: [],
    MOTORCYCLE: [],
  },
  Volkswagen: {
    CAR: ['Polo', 'Golf', 'Jetta', 'Passat', 'Arteon', 'Beetle', 'ID.3', 'ID.4', 'ID.7'],
    SUV: ['T-Cross', 'T-Roc', 'Taos', 'Tiguan', 'Touareg', 'Atlas'],
    PICKUP: ['Amarok'],
    VAN: ['Caddy', 'Transporter', 'Caravelle', 'Multivan', 'Crafter'],
    SMALL_TRUCK: ['Caddy Cargo', 'Transporter Chassis', 'Crafter Chassis'],
    MEDIUM_TRUCK: ['Crafter Chassis', 'Delivery', 'Constellation'],
    TOW_TRUCK: ['Crafter Chassis', 'Delivery', 'Constellation', 'Other Volkswagen chassis'],
    OPEN_CAR_CARRIER: ['Crafter Chassis', 'Delivery', 'Constellation', 'Other Volkswagen chassis'],
    ENCLOSED_CARRIER: ['Crafter Chassis', 'Constellation', 'Other Volkswagen chassis'],
    MOTORCYCLE: [],
  },
  Volvo: {
    CAR: ['S40', 'S60', 'S90', 'V40', 'V60', 'V90'],
    SUV: ['XC40', 'XC60', 'XC90', 'C40', 'EX30', 'EX90'],
    PICKUP: [],
    VAN: [],
    SMALL_TRUCK: ['FL'],
    MEDIUM_TRUCK: ['FL', 'FE', 'FM', 'FMX', 'FH', 'VNL'],
    TOW_TRUCK: ['FL', 'FE', 'FM', 'FMX', 'FH', 'Other Volvo chassis'],
    OPEN_CAR_CARRIER: ['FL', 'FE', 'FM', 'FH', 'Other Volvo chassis'],
    ENCLOSED_CARRIER: ['FE', 'FM', 'FH', 'Other Volvo chassis'],
    MOTORCYCLE: [],
  },
  Scania: {
    CAR: [],
    SUV: [],
    PICKUP: [],
    VAN: [],
    SMALL_TRUCK: [],
    MEDIUM_TRUCK: ['P-Series', 'G-Series', 'R-Series', 'S-Series', 'L-Series'],
    TOW_TRUCK: ['P-Series', 'G-Series', 'R-Series', 'S-Series', 'Other Scania chassis'],
    OPEN_CAR_CARRIER: ['P-Series', 'G-Series', 'R-Series', 'S-Series', 'Other Scania chassis'],
    ENCLOSED_CARRIER: ['P-Series', 'G-Series', 'R-Series', 'S-Series', 'Other Scania chassis'],
    MOTORCYCLE: [],
  },
  MAN: {
    CAR: [],
    SUV: [],
    PICKUP: [],
    VAN: ['TGE'],
    SMALL_TRUCK: ['TGE', 'TGL'],
    MEDIUM_TRUCK: ['TGL', 'TGM', 'TGS', 'TGX'],
    TOW_TRUCK: ['TGL', 'TGM', 'TGS', 'TGX', 'Other MAN chassis'],
    OPEN_CAR_CARRIER: ['TGM', 'TGS', 'TGX', 'Other MAN chassis'],
    ENCLOSED_CARRIER: ['TGM', 'TGS', 'TGX', 'Other MAN chassis'],
    MOTORCYCLE: [],
  },
  DAF: {
    CAR: [],
    SUV: [],
    PICKUP: [],
    VAN: [],
    SMALL_TRUCK: ['LF', 'XD'],
    MEDIUM_TRUCK: ['LF', 'CF', 'XD', 'XF', 'XG', 'XG+'],
    TOW_TRUCK: ['LF', 'CF', 'XD', 'XF', 'Other DAF chassis'],
    OPEN_CAR_CARRIER: ['LF', 'CF', 'XD', 'XF', 'Other DAF chassis'],
    ENCLOSED_CARRIER: ['CF', 'XD', 'XF', 'XG', 'Other DAF chassis'],
    MOTORCYCLE: [],
  },
  Iveco: {
    CAR: [],
    SUV: [],
    PICKUP: [],
    VAN: ['Daily'],
    SMALL_TRUCK: ['Daily Chassis Cab', 'Eurocargo'],
    MEDIUM_TRUCK: ['Eurocargo', 'S-Way', 'T-Way', 'X-Way', 'Stralis', 'Trakker'],
    TOW_TRUCK: ['Daily Chassis Cab', 'Eurocargo', 'S-Way', 'T-Way', 'Other Iveco chassis'],
    OPEN_CAR_CARRIER: ['Eurocargo', 'S-Way', 'X-Way', 'Other Iveco chassis'],
    ENCLOSED_CARRIER: ['Eurocargo', 'S-Way', 'Other Iveco chassis'],
    MOTORCYCLE: [],
  },
  Hino: {
    CAR: [],
    SUV: [],
    PICKUP: [],
    VAN: [],
    SMALL_TRUCK: ['Dutro', '300 Series', '155', '195'],
    MEDIUM_TRUCK: ['500 Series', '700 Series', '268', '338', 'Profia'],
    TOW_TRUCK: ['Dutro', '300 Series', '500 Series', '268', '338', 'Other Hino chassis'],
    OPEN_CAR_CARRIER: ['300 Series', '500 Series', '268', '338', 'Other Hino chassis'],
    ENCLOSED_CARRIER: ['500 Series', '700 Series', 'Other Hino chassis'],
    MOTORCYCLE: [],
  },
  Fuso: {
    CAR: [],
    SUV: [],
    PICKUP: [],
    VAN: ['Rosa'],
    SMALL_TRUCK: ['Canter', 'eCanter'],
    MEDIUM_TRUCK: ['Canter', 'Fighter', 'Super Great', 'FA', 'FI', 'FJ'],
    TOW_TRUCK: ['Canter', 'Fighter', 'Super Great', 'Other Fuso chassis'],
    OPEN_CAR_CARRIER: ['Canter', 'Fighter', 'Other Fuso chassis'],
    ENCLOSED_CARRIER: ['Canter', 'Fighter', 'Super Great', 'Other Fuso chassis'],
    MOTORCYCLE: [],
  },
  Tata: {
    CAR: ['Nano', 'Tiago', 'Tigor', 'Altroz'],
    SUV: ['Punch', 'Nexon', 'Harrier', 'Safari'],
    PICKUP: ['Xenon', 'Yodha'],
    VAN: ['Winger', 'Magic'],
    SMALL_TRUCK: ['Ace', 'Intra', 'Yodha'],
    MEDIUM_TRUCK: ['Ultra', 'Signa', 'Prima', 'LPT'],
    TOW_TRUCK: ['Ace', 'Intra', 'Ultra', 'Signa', 'Other Tata chassis'],
    OPEN_CAR_CARRIER: ['Ultra', 'Signa', 'Prima', 'Other Tata chassis'],
    ENCLOSED_CARRIER: ['Ultra', 'Signa', 'Prima', 'Other Tata chassis'],
    MOTORCYCLE: [],
  },
  Mahindra: {
    CAR: ['KUV100'],
    SUV: ['Bolero', 'Scorpio', 'Scorpio-N', 'XUV300', 'XUV500', 'XUV700', 'Thar', 'Marazzo'],
    PICKUP: ['Bolero Pik-Up', 'Imperio', 'Scorpio Getaway'],
    VAN: ['Supro'],
    SMALL_TRUCK: ['Jeeto', 'Supro', 'Maxximo', 'Bolero Pik-Up'],
    MEDIUM_TRUCK: ['Furio', 'Blazo'],
    TOW_TRUCK: ['Bolero Pik-Up', 'Furio', 'Blazo', 'Other Mahindra chassis'],
    OPEN_CAR_CARRIER: ['Furio', 'Blazo', 'Other Mahindra chassis'],
    ENCLOSED_CARRIER: ['Furio', 'Blazo', 'Other Mahindra chassis'],
    MOTORCYCLE: [],
  },
  Peugeot: {
    CAR: ['108', '206', '207', '208', '301', '307', '308', '407', '508'],
    SUV: ['2008', '3008', '5008'],
    PICKUP: ['Landtrek'],
    VAN: ['Partner', 'Rifter', 'Expert', 'Traveller', 'Boxer'],
    SMALL_TRUCK: ['Partner', 'Expert', 'Boxer Chassis Cab'],
    MEDIUM_TRUCK: ['Boxer Chassis Cab', 'Other Peugeot chassis'],
    TOW_TRUCK: ['Boxer Chassis Cab', 'Other Peugeot chassis'],
    OPEN_CAR_CARRIER: ['Boxer Chassis Cab', 'Other Peugeot chassis'],
    ENCLOSED_CARRIER: ['Boxer Chassis Cab', 'Other Peugeot chassis'],
    MOTORCYCLE: [],
  },
  Renault: {
    CAR: ['Twingo', 'Clio', 'Megane', 'Symbol', 'Talisman', 'Fluence'],
    SUV: ['Captur', 'Kadjar', 'Koleos', 'Arkana', 'Duster'],
    PICKUP: ['Alaskan', 'Duster Oroch'],
    VAN: ['Kangoo', 'Express', 'Trafic', 'Master'],
    SMALL_TRUCK: ['Kangoo Van', 'Trafic Chassis', 'Master Chassis Cab'],
    MEDIUM_TRUCK: ['Master Chassis Cab', 'Midlum', 'D-Series'],
    TOW_TRUCK: ['Master Chassis Cab', 'Midlum', 'D-Series', 'Other Renault chassis'],
    OPEN_CAR_CARRIER: ['Master Chassis Cab', 'D-Series', 'Other Renault chassis'],
    ENCLOSED_CARRIER: ['Master Chassis Cab', 'D-Series', 'Other Renault chassis'],
    MOTORCYCLE: [],
  },
  Suzuki: {
    CAR: ['Alto', 'Celerio', 'Swift', 'Baleno', 'Dzire', 'Ciaz', 'Ignis'],
    SUV: ['Vitara', 'Grand Vitara', 'S-Cross', 'Jimny', 'Ertiga', 'XL7'],
    PICKUP: ['Equator'],
    VAN: ['Carry', 'APV', 'Every'],
    SMALL_TRUCK: ['Carry', 'Super Carry'],
    MEDIUM_TRUCK: [],
    TOW_TRUCK: ['Carry', 'Super Carry', 'Other Suzuki chassis'],
    OPEN_CAR_CARRIER: ['Other Suzuki chassis'],
    ENCLOSED_CARRIER: ['Other Suzuki chassis'],
    MOTORCYCLE: ['GN125', 'GSX-R125', 'GSX-R600', 'GSX-R750', 'GSX-R1000', 'Gixxer', 'V-Strom 250', 'V-Strom 650', 'V-Strom 1050', 'Hayabusa', 'Burgman'],
  },
  Honda: {
    CAR: ['Civic', 'Accord', 'City', 'Jazz', 'Fit', 'Insight'],
    SUV: ['HR-V', 'CR-V', 'ZR-V', 'Pilot', 'Passport'],
    PICKUP: ['Ridgeline'],
    VAN: ['Odyssey', 'Stepwgn', 'Acty Van'],
    SMALL_TRUCK: ['Acty Truck'],
    MEDIUM_TRUCK: [],
    TOW_TRUCK: ['Other Honda chassis'],
    OPEN_CAR_CARRIER: [],
    ENCLOSED_CARRIER: [],
    MOTORCYCLE: ['CB125F', 'CB300R', 'CB500F', 'CB650R', 'CB1000R', 'CBR500R', 'CBR600RR', 'CBR1000RR', 'Africa Twin', 'Gold Wing', 'Rebel 300', 'Rebel 500', 'PCX', 'Forza'],
  },
  Yamaha: {
    CAR: [],
    SUV: [],
    PICKUP: [],
    VAN: [],
    SMALL_TRUCK: [],
    MEDIUM_TRUCK: [],
    TOW_TRUCK: [],
    OPEN_CAR_CARRIER: [],
    ENCLOSED_CARRIER: [],
    MOTORCYCLE: ['YBR125', 'FZ', 'FZ-S', 'MT-03', 'MT-07', 'MT-09', 'MT-10', 'YZF-R3', 'YZF-R6', 'YZF-R1', 'TMAX', 'XMAX', 'NMAX', 'Tenere 700', 'Tracer 7', 'Tracer 9', 'Bolt', 'V Star'],
  },
  'Harley-Davidson': {
    CAR: [],
    SUV: [],
    PICKUP: [],
    VAN: [],
    SMALL_TRUCK: [],
    MEDIUM_TRUCK: [],
    TOW_TRUCK: [],
    OPEN_CAR_CARRIER: [],
    ENCLOSED_CARRIER: [],
    MOTORCYCLE: ['Sportster', 'Iron 883', 'Forty-Eight', 'Street 750', 'Street Bob', 'Fat Bob', 'Fat Boy', 'Low Rider', 'Softail Standard', 'Road King', 'Street Glide', 'Road Glide', 'Electra Glide', 'Pan America', 'Nightster'],
  },
  Ducati: {
    CAR: [],
    SUV: [],
    PICKUP: [],
    VAN: [],
    SMALL_TRUCK: [],
    MEDIUM_TRUCK: [],
    TOW_TRUCK: [],
    OPEN_CAR_CARRIER: [],
    ENCLOSED_CARRIER: [],
    MOTORCYCLE: ['Monster', 'Scrambler Icon', 'Scrambler Desert Sled', 'Panigale V2', 'Panigale V4', 'Streetfighter V2', 'Streetfighter V4', 'Multistrada V2', 'Multistrada V4', 'Diavel', 'XDiavel', 'Hypermotard', 'SuperSport', 'DesertX'],
  },
} as const satisfies Record<string, Record<VehicleModelType, readonly string[]>>;

export type VehicleBrand = keyof typeof VEHICLE_MODELS_BY_BRAND_AND_TYPE;
