import React from 'react';
import { act, create } from 'react-test-renderer';
import { TextInput } from 'react-native';
import { DriverPhoneAuthScreen } from './driver-phone-auth-screen';
import { MarketSelector } from './market-selector';
import { sendDriverPhoneVerificationCode } from '@/lib/api';
import { readTrustedDriverSession } from '@/lib/auth-storage';
const mockRouter = { push: jest.fn(), replace: jest.fn() };
const mockContinue = jest.fn();
jest.mock('expo-router', () => ({ useRouter: () => mockRouter }));
jest.mock('react-i18next', () => ({ useTranslation: () => ({ t: key => key }) }));
jest.mock('@/components/market-selector', () => ({ MarketSelector: () => null }));
jest.mock('@/context/auth-context', () => ({ useAuth: () => ({ continueWithTrustedSession: mockContinue }) }));
jest.mock('@/lib/api', () => ({ sendDriverPhoneVerificationCode: jest.fn() }));
jest.mock('@/lib/auth-storage', () => ({ readTrustedDriverSession: jest.fn() }));
jest.mock('@/localization/provider', () => ({ useAppLanguage: () => ({ hasSavedLanguage: true, isRTL: false }) }));
jest.mock('@/hooks/use-android-keyboard-inset', () => ({ useAndroidKeyboardInset: () => 0 }));
let tree;
beforeEach(() => { jest.clearAllMocks(); readTrustedDriverSession.mockResolvedValue(null); });
afterEach(async () => { if (tree) await act(async () => tree.unmount()); tree = null; });
it.each(['login', 'register'])('requires a market and preserves it through %s OTP navigation', async mode => {
  await act(async () => { tree = create(<DriverPhoneAuthScreen mode={mode} />); });
  const phone = () => tree.root.findAllByType(TextInput).find(node => node.props.accessibilityLabel === 'Phone number');
  await act(async () => phone().props.onChangeText('70123456'));
  await act(async () => phone().props.onSubmitEditing());
  expect(sendDriverPhoneVerificationCode).not.toHaveBeenCalled();
  await act(async () => tree.root.findByType(MarketSelector).props.onChange('FR'));
  if (mode === 'register') await act(async () => tree.root.findAll(node => node.props.accessibilityRole === 'checkbox' && typeof node.props.onPress === 'function')[0].props.onPress());
  await act(async () => phone().props.onSubmitEditing());
  expect(sendDriverPhoneVerificationCode).toHaveBeenCalledWith({ phoneNumber: '+96170123456', marketCode: 'FR' });
  expect(mockRouter[mode === 'login' ? 'push' : 'replace']).toHaveBeenCalledWith({ pathname: '/verify-phone', params: { phoneNumber: '+96170123456', marketCode: 'FR' } });
});
it('sends explicit market to trusted continuation and stays on login after a mismatch', async () => {
  readTrustedDriverSession.mockResolvedValue({ phoneNumber: '+33123456789' });
  mockContinue.mockResolvedValue({ status: 'unavailable', message: 'Choose your home market' });
  await act(async () => { tree = create(<DriverPhoneAuthScreen mode="login" />); });
  await act(async () => tree.root.findByType(MarketSelector).props.onChange('LB'));
  await act(async () => tree.root.findAll(node => node.props.accessibilityRole === 'button' && typeof node.props.onPress === 'function')[0].props.onPress());
  expect(mockContinue).toHaveBeenCalledWith('LB');
  expect(mockRouter.replace).not.toHaveBeenCalled();
  expect(JSON.stringify(tree.toJSON())).toContain('Choose your home market');
});
